package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gogo'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gogo")) {
    expectSteps {
        script {
            name = "Vivado"
            scriptContent = """
                set -e -x
                /home/Xilinx/Vivado/2019.2/bin/vivado -mode batch -source top.tcl
            """.trimIndent()
        }
        script {
            name = "Peta"
            scriptContent = """
                set -e -x
                p/peta.sh
            """.trimIndent()
        }
    }
    steps {
        insert(0) {
            step {
                name = "Create"
                type = "Vivado"
                param("VivadoTCL", "create.tcl")
            }
        }
        items.removeAt(1)
        insert(2) {
            step {
                name = "Synth"
                type = "Vivado"
                param("VivadoTCL", "synth.tcl")
            }
        }
    }
}
